# server_node.py

class ServerNode:
    def __init__(self, server_id):
        self.server_id = server_id

    def process_request(self, request):
        """
        Simulates processing a request by a server node.

        Parameters:
        - request (str): The request to be processed.

        Returns:
        - str: The response generated by the server node.
        """
        print(f"Server {self.server_id} processing request: {request}")
        # In a real system, this is where you would process the request
        # and generate a response. For the sake of simulation, return a placeholder response.
        return f"Response from Server {self.server_id}: Request '{request}' processed successfully"
